# Server Machine Datase (SMD)

https://github.com/NetManAIOps/OmniAnomaly

In [3]:
import numpy as np

data = np.load("../data/raw/TimesNet-datasets/SMD/SMD_train.npy")
data.shape

(708405, 38)

In [4]:
import pandas as pd

df = pd.DataFrame(data)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,28,29,30,31,32,33,34,35,36,37
0,0.010101,0.001642,0.001996,0.002630,0.0,0.987293,0.059893,0.0,0.0,0.000000,...,0.0,0.2,0.100698,0.000000,0.0,0.030769,0.141966,0.141966,0.0,0.0
1,0.010101,0.000626,0.001553,0.002391,0.0,0.834117,0.060428,0.0,0.0,0.000678,...,0.0,0.2,0.082419,0.051948,0.0,0.035165,0.149766,0.149766,0.0,0.0
2,0.010101,0.000235,0.001109,0.002152,0.0,0.681114,0.061497,0.0,0.0,0.001055,...,0.0,0.2,0.088069,0.000000,0.0,0.030769,0.135725,0.135725,0.0,0.0
3,0.010101,0.000938,0.001109,0.002152,0.0,0.681462,0.060963,0.0,0.0,0.000000,...,0.0,0.2,0.093054,0.012987,0.0,0.035165,0.148206,0.148206,0.0,0.0
4,0.010101,0.001173,0.001220,0.002152,0.0,0.681462,0.060428,0.0,0.0,0.000000,...,0.0,0.2,0.109339,0.025974,0.0,0.030769,0.154446,0.154446,0.0,0.0

In [5]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,28,29,30,31,32,33,34,35,36,37
count,708405.000000,708405.000000,708405.000000,708405.000000,708405.000000,708405.000000,708405.000000,708405.0,708405.000000,708405.000000,...,708405.000000,708405.000000,708405.000000,708405.000000,708405.000000,708405.000000,708405.000000,708405.000000,708405.000000,708405.000000
mean,0.135608,0.070325,0.081224,0.095481,0.263753,0.722551,0.394186,0.0,0.020008,0.001013,...,0.000016,0.100355,0.191688,0.105285,0.035761,0.057729,0.214860,0.210742,0.016665,0.009591
std,0.137656,0.110738,0.128426,0.157387,0.416208,0.294917,0.323389,0.0,0.051387,0.010984,...,0.003382,0.138886,0.186882,0.148589,0.083560,0.107484,0.204569,0.206808,0.070894,0.059140
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.032258,0.003363,0.004544,0.005624,0.000000,0.452556,0.147541,0.0,0.000187,0.000000,...,0.000000,0.000605,0.042095,0.000000,0.000000,0.009009,0.045317,0.040404,0.000000,0.000000
50%,0.090909,0.023305,0.029070,0.031166,0.000000,0.859100,0.285954,0.0,0.003787,0.000000,...,0.000000,0.021505,0.136832,0.047349,0.000000,0.022989,0.155863,0.147628,0.000000,0.000000
75%,0.193548,0.081597,0.088327,0.096535,0.652174,0.983467,0.683879,0.0,0.016135,0.000002,...,0.000000,0.172414,0.294752,0.147436,0.023256,0.051064,0.314286,0.314536,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.888497,0.888497

In [ ]:
import plotly.graph_objects as go

downsample_factor = 1
df_downsampled = df.iloc[::downsample_factor]

fig = go.Figure()
for col in df_downsampled.columns:
    fig.add_trace(
        go.Scatter(
            x=df_downsampled.index,
            y=df_downsampled[col],
            mode='lines',
            name=col
        )
    )
index_label = "Datetime" if isinstance(df_downsampled.index, pd.DatetimeIndex) else "Index"
fig.update_layout(
    title=f"SMD | original shape: {df.shape} | plot downsample factor: {downsample_factor}",
    xaxis_title=index_label,
    yaxis_title="Value",
    legend=dict(
        title="Columns",
        orientation="v",
        x=1.02,
        xanchor="left",
        y=1
    )
)
fig.show()

In [ ]:
df.to_csv("../data/processed/SMD_train.csv", index=False)